#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: deploy vRealize Business  OVA
  include: vrealizebova_deploy.yml tags=vrbova_deploy
- name: Power Vrealize Business
  include: vrealizeb_poweron.yml tags=vrb_poweron
- name: Delete Vrealize Business
  include: vrealizeb_delete.yml tags=vrb_delete
- name: configure vRB SSO
  include: vrealizeb_sso.yml tags=vrb_sso
- name: toggle vRB SSH
  include: vrealizeb_toggle_ssh.yml tags=vrb_toggle_ssh
- name: configure vRB Time Settings
  include: vrealizeb_time.yml tags=vrb_time_settings
- name: configure vRB Network
  include: vrealizeb_network.yml tags=vrb_network
- name: configure vRB HTTP Proxy
  include: vrealizeb_http_proxy.yml tags=vrb_http_proxy
- name: configure vRB SSL Certificates
  include: vrealizeb_ssl_certificate.yml tags=vrb_ssl_certificate
