#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: Start vrb
  vsphere_guest:
    vcenter_hostname: "{{ mgmt_vc }}"
    username: "{{ mgmt_vc_username }}"
    password: "{{ mgmt_vc_password }}"
    guest: "{{ vrealizeb_name }}"
    force: yes
    state: powered_on
  register: vrb_poweron

- name: debug checking vrb Instance is created
  debug: var=vrb_poweron
