#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
- name: Notice -- Waiting on vRBusiness API availability.
  wait_for: host="{{ vrb_host_name }}" port=5480 delay=30 timeout=3600

# TODO: this really is a 'timed delay' and should actually check the DB port.
- name: Notice -- Waiting briefly for databases to settle.
  wait_for: host="{{ vrb_host_name }}" port=5480 delay=30 timeout=600

- name: Toggle SSH
  template:
    src: toggle_ssh_request_body.xml
    dest: "{{toggle_ssh_request_body_file }}"

- name: register with vra
  uri:
    url: https://{{ vrb_host_name }}:5480/service/administration/config-page.py
    method: POST
    force_basic_auth: yes
    follow_redirects: all
    user: "{{ vrb_default_admin_user }}"
    password: "{{ vrealizeb_itfm_root_password }}"
    HEADER_Content-Type: "application/xml"
    body:  "{{ lookup('file',toggle_ssh_request_body_file) }}"
    validate_certs: no
    timeout: 120
    status_code: 200
  register: register_result

- debug: msg="{{ register_result }}"

